apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-api
  name: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-api
    spec:
      containers:
      - image: tylerjf1993/demo-api:latest
        name: demo-api
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-api
  name: demo-api
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-api
  type: ClusterIP
status:
  loadBalancer: {}
