spring:
  application:
    sales-config:
      attributes: null
      description: "When you purchase this option, you will receive one Tile NFT. Hopefully it's rare! Enjoy and customize your tile!"
      name: "Tile NFT Sale"
      get_image_url_postfix: "/api/image/saleImage/get/1"