spring:
  application:
    token-config:
      base_name: "Tile #"
      description: "This is a rare TileNFT! Customize your TileNFT artwork. Or merge two TileNFTs to create a third TileNFT that's even more rare. Use TileNFT.io for customizing and merging TileNFTs."
      base_external_url_postfix: "/?tokenId="
      base_image_url_postfix: "/api/image/tile/get/"
      background_color: null # maybe we should add a background_color?
      base_animation_url: null
      base_youtube_url: null
      # attributes key will be decided by *token-config.yaml
