spring:
  application:
    alchemyAPIKey: "cM6mpgOs8PlQFVgeYtPIW-fUzy5L5tC8"
    alchemyBaseUrl: "https://eth-rinkeby.alchemyapi.io/v2/"
  datasource:
    password: "kksb2iA18s22jaIk"

  profiles:
    include:
      - default
      - traits-config
      - token-config
      - contract-config
      - sales-config
      - events-config

  cloud:
    gcp:
      sql:
        database-name: "db1"
        instance-connection-name: "dev-eth-api:us-east4:sql-1"

server:
  error:
    path: "/error"