application-traits-config:
  yaml:
spring:
  application:
    token-config:
      name: a
      description: b
      image: c
      external_url: d
      background_color: null
      animation_url: null
      youtube_url: null