spring:
  application:
    contract-config:
      name: a
      description: b
      image: c
      external_link: d
      seller_fee_basis_points: 100 # Indicates a 1% seller fee.
      fee_recipient: "0x4fdF8DF271e1A65B119D858eeA2A7681da8F9c15" # Where seller fees will be paid to.
