spring:
  application:
    name: tile-nft
    tileCount: 1
    bitsPerTile: 24
    alchemyAPIKey: "cM6mpgOs8PlQFVgeYtPIW-fUzy5L5tC8"
    alchemyBaseUrl: "https://eth-rinkeby.alchemyapi.io/v2/"
    nftContractAddress: "0x4aDA40511688d551630B353bAec821F7289A3Dd5"
    nftFactoryContractAddress: "0xD6cC4672310D823186874da35616AD9619c63971"
    mintEventHashSignature: "0x070aa035fe0a09f0d9305bdc2d7a5d93cd4733db3b1ff869b4a7033c9501909a"
    schedulerFixedRateMs: 20000
    schedulerNumberOfBlocksToLookBack: 200000
    nftName: "tileNFT"
    nftExternalUrl: "http://tilenft.io/"
    nftBaseImageUrl: "http://tilenft.io/image/"
    nftDescription: "A TileNFT. Trade, customize, and level up your TileNFT!!!"

  profiles:
    include:
      - default
      - traits-config
      - token-config
      - contract-config
      - sales-config

  cloud:
    gcp:
      sql:
        database-name: "db1"
        instance-connection-name: "dev-eth-api:us-east4:sql-1"

  datasource:
    continue-on-error: true
    initialization-mode: always
    password: "kksb2iA18s22jaIk"
