spring:
  application:
    name: tile-nft
    tileCount: 1
    bitsPerTile: 24
    alchemyAPIKey: "cM6mpgOs8PlQFVgeYtPIW-fUzy5L5tC8"
    alchemyBaseUrl: "https://eth-rinkeby.alchemyapi.io/v2/"
    nftContractAddress: "0x29502a8DE72Ad5A33C26E2e407c8E1e0E3a5a3F7"
    nftFactoryContractAddress: "0x1b78Cd0aa89a34B865231eaaDd86E9b13cC97064"
    mintEventHashSignature: "0x070aa035fe0a09f0d9305bdc2d7a5d93cd4733db3b1ff869b4a7033c9501909a"
  cloud:
    gcp:
      sql:
        database-name: "db1"
        instance-connection-name: "sql-1"
  datasource:
    continue-on-error: true
    initialization-mode: always
    password: "kksb2iA18s22jaIk"
