spring:
  application:
    traits-config:
      types:
        - color
        - shape
        - mood
      weights:
        - {id: null, traitTypeWeightId: 1, traitTypeId: 3, likelihood: 4, value: foo, displayTypeValue: bar}
        - {id: null, traitTypeWeightId: 2, traitTypeId: 3, likelihood: 4, value: foo, displayTypeValue: bar}